import type { DinoNeed, PlayMode } from '../game/GameModel';
import type { DinoPersonality, DinoSpecies } from '../game/DinoSpecies';

declare global {
  interface Window {
    __DINOLAND__?: {
      getState: () => {
        mode: PlayMode;
        eggTaps: number;
        eggBusy: boolean;
        need: DinoNeed | null;
        secondNeed: DinoNeed | null;
        needs: Array<DinoNeed | null>;
        hearts: number;
        heartTarget: number;
        scoreText: string;
        fireControlSymbol: string;
        cannonLoaded: 'apple' | 'ball' | 'water' | 'music' | 'heart' | null;
        cannonPower: number;
        lastCannonPower: number;
        lastCannonSpeed: number;
        lastShotWallBounces: number;
        lastShotHitDino: boolean;
        lastDinoImpactSpeed: number;
        cannonShotActive: boolean;
        cannonAngle: number;
        cannonGuideEndX: number;
        cannonGuideEndY: number;
        movingObjectCount: number;
        firstDinoBouncing: boolean;
        secondDinoBouncing: boolean;
        bouncingDinoCount: number;
        firstBounceSpeed: number;
        cannonDinoCollisions: number;
        firstCannonDistance: number;
        dinoCount: number;
        dinoTypes: DinoSpecies[];
        dinoPersonalities: DinoPersonality[];
        riggedDinoCount: number;
        firstDinoMotion: 'idle' | 'walk' | 'happy' | 'eat' | 'impact' | null;
        dinoScales: number[];
        dinoCareCounts: number[];
        newEggUnlocked: boolean;
        secondEggVisible: boolean;
        secondEggTaps: number;
        secondEggBusy: boolean;
        secondDinoVisible: boolean;
        secondDinoAlpha: number;
        firstBubbleVisible: boolean;
        firstBubbleItem: string | null;
        secondBubbleVisible: boolean;
        secondBubbleAlpha: number;
        secondBubbleX: number;
        secondBubbleY: number;
        firstBubbleAlpha: number;
        firstBubbleX: number;
        firstBubbleY: number;
        fieldItemCount: number;
        fieldItems: Array<{ type: 'apple' | 'ball' | 'water' | 'music' | 'heart' | null; x: number; y: number }>;
        unlockedSlots: number;
        lootReady: boolean;
        lootVisible: boolean;
        cannonBoostReady: boolean;
        magicSlotSymbol: string;
        soundMuted: boolean;
        heartTextures: string[];
        lootCelebrationVisible: boolean;
        lootX: number;
        lootY: number;
        eggX: number;
        eggY: number;
        secondEggX: number;
        secondEggY: number;
        dinoX: number;
        dinoY: number;
        secondDinoX: number;
        secondDinoY: number;
        dinoDistance: number;
        firstRewardEggDistance: number;
      };
      forceNeed: (dinoIndex: number, need: DinoNeed) => DinoNeed | null;
      pauseDino: (dinoIndex: number) => void;
      fulfillActiveNeed: (dinoIndex: number) => boolean;
      placeDino: (dinoIndex: number, x: number, y: number) => boolean;
      launchDino: (dinoIndex: number, vx: number, vy: number) => boolean;
      resumeDino: (dinoIndex: number) => boolean;
      placeCareItem: (need: DinoNeed, x: number, y: number) => boolean;
    };
  }
}

export {};
